require('jv.plugins_conf.mini')
require('jv.plugins_conf.autosave')
require('jv.plugins_conf.telescope')
-- require('jv.plugins_conf.gruvbox')
-- require('jv.plugins_conf.gruvbox-baby')
require('jv.plugins_conf.gruvbox-material')
-- require('jv.plugins_conf.airline')
require('jv.plugins_conf.lualine')
require('jv.plugins_conf.luasnip')
require('jv.plugins_conf.undotree')
require('jv.plugins_conf.fugitive')
require('jv.plugins_conf.treesitter')
require('jv.plugins_conf.lsp')
require('jv.plugins_conf.nvimtree')
require('jv.plugins_conf.barbar')
require('jv.plugins_conf.indent')
require('jv.plugins_conf.exercism')
require('jv.plugins_conf.notify')
require('jv.plugins_conf.gitsigns')
require('jv.plugins_conf.null-ls')
require('jv.plugins_conf.colorizer')
