local builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader>pf', builtin.find_files, {})
vim.keymap.set('n', '<leader>pg', builtin.git_files, {})
vim.keymap.set('n', '<leader>pd', builtin.lsp_document_symbols, {})
vim.keymap.set('n', '<leader>pm', builtin.marks, {})
vim.keymap.set('n', '<leader>pa', builtin.fd, {})
vim.keymap.set('n', '<leader>ps', function()
	builtin.grep_string({ search = vim.fn.input("Grep > ")})
end)
